services:
  event-hub:
    build:
      context: .
    container_name: event-hub
    env_file:
      - .env
    environment:
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped
